### ISSUE TITLE
Encoder error

### ISSUE THREAD

**Issue by amikumanto** [e00E/obs-amf#10]
Hi,
I recently started using this plugin since the other one has been dropping a lot of frames for me. That seems to have fixed the problem, but now I have an issue where the encoder will sometimes error out. Looking at my log files I think this is what the error says, which I'm not sure is super helpful?
```
02:55:22.159: amftest: send_frame_to_encoder: SubmitInput: 25
02:55:22.159: Error encoding with encoder 'recording_h264'
```
I've noticed that the errors seem to somewhat correspond to more graphically taxing situations (e.g. it errored out two or three times in the cutscene [shown in this video](https://www.youtube.com/watch?v=qY77II31xnQ), especially around when there were lots of explosions on screen), however I've kept an eye on task manager and my gpu is never taxed to 100%, even when I specifically look at the codec usage so I wouldn't think the issue is my gpu? Though maybe I just don't know enough about video encoding haha 😅 Any help would be appreciated!!

**Comment by e00E** [comment]
I think the problem is that we treat a soft errors like one frame getting dropped for whatever reason as a hard error. This is on my mind to fix.
