### ISSUE TITLE
HEVC GPU produces a black screen

### ISSUE THREAD

**Issue by amikumanto** [e00E/obs-amf#11]
I have a Radeon RX 5600 XT and when the option AMF HEVC GPU is selected, recordings come out as a black screen? This isn't a massive issue for me since I'm fine just using the H264 option, but it's a little disappointing to find out after the fact that your recording is actually audio-only
(also sorry I don't use github that much, I hope I'm not spamming the issues or anything?)

**Comment by e00E** [comment]
You're not spamming These issues are good.

I don't know what the problem is. If you didn't get any errors during encoding then plugin thinks everything worked correctly but clearly it didn't. You could try playing around with some of the settings to see if that helps but if you're not familiar with the AMF internals and what the settings mean then it probably isnt' going to be fruitful.
Maybe the simplest thing to try is lowering the recording resolution and frame rate.

**Comment by amikumanto** [comment]
Oh okay thank you! I haven't gotten a chance to test it with different settings yet but I decided to try running it through ffmpeg and I have a couple notes that might be helpful?

First, there definitely *is* a video stream, even if it doesn't contain anything useful. The video gets detected as HEVC at the correct resolution and framerate, and when I tried remuxing it into an audio-only .mka, the filesize dropped from ~25mb to ~800kb (for reference, my h264 footage is typically ~200-600mb)

Second, when I tried running it through ffmpeg, I got this string of errors:
```
[hevc @ 00000262a0d48ac0] VPS 0 does not exist
[hevc @ 00000262a0d48ac0] SPS 0 does not exist.
[hevc @ 00000262a0d48ac0] PPS id out of range: 0
[hevc @ 00000262a0d48ac0] Error parsing NAL unit #1.
...
[hevc @ 00000262a0d48ac0] PPS id out of range: 0
[hevc @ 00000262a0d48ac0] Error parsing NAL unit #1.
[matroska,webm @ 00000262a0d47300] decoding for stream 0 failed
[matroska,webm @ 00000262a0d47300] Could not find codec parameters for stream 0 (Video: hevc, none(tv, bt709), 2560x1440): unspecified pixel format
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
```
(the PPS and NAL errors repeat 300 times each)

I suspect the first errors with VPS and SPS aren't the issue since the old HEVC plugin also produces those, though ffmpeg encoding with `-c:v amf_hevc` doesn't so it still might be worth looking into at some point? Either way I hope these are of some use!!

**Comment by amikumanto** [comment]
Closing this issue because I realized I didn't have the correct driver version and updating seems to have fixed it -_-

Apologies for the confusion!!
