### ISSUE TITLE
QvbrQualityLevel error

### ISSUE THREAD

**Issue by nbstk1** [e00E/obs-amf#23]
Problem only in h264 encoding, both gpu and cpu versions
Older plugin versions return me error SetProperty ColorBitDepth 8

Driver: 22.3.1
GPU: Vega 56
OBS: 27.2.4
Plugin: 0.2.0

Error in log

amftest: AMF runtime version    : 1.4.24 build 0 raw 0
amftest: AMF compiletime version: 1.4.24 build 0 raw 0
amftest: SetProperty Usage 0
amftest: SetProperty Profile 100
amftest: SetProperty ProfileLevel 42
amftest: SetProperty LowLatencyInternal false
amftest: SetProperty RateControlMethod 0
amftest: SetProperty TargetBitrate 10000000
amftest: SetProperty PeakBitrate 30000000
amftest: SetProperty RateControlSkipFrameEnable false
amftest: SetProperty MinQP 18
amftest: SetProperty MaxQP 46
amftest: SetProperty QPI 26
amftest: SetProperty QPP 26
amftest: SetProperty QPB 26
amftest: SetProperty QvbrQualityLevel 23
amftest: Error: Plugin::Plugin: SetProperty QvbrQualityLevel 23

**Comment by e00E** [comment]
Related to https://github.com/e00E/obs-amf/issues/5 .

It looks like we do need the "ignore SetProperty" change after all. I will also report this to AMD.

**Comment by nbstk1** [comment]
Thank you for an answer. I hope AMD will make changes asap or we will get a workaround until that, if that is possible

**Comment by nbstk1** [comment]
Can confirm that it works on Vega gpu's with VCE 4.0 from version 0.2.1 with driver 22.3.1
![log](https://user-images.githubusercontent.com/103155450/171794972-1ef83981-e9ef-4377-ba74-e494cb1d9032.png)
