### ISSUE TITLE
Plugin doesnt work on RX580 with  QVBR Quality

### ISSUE THREAD

**Issue by bisher13** [e00E/obs-amf#27]
the last plugin update  doesnt work with  my rx580 or its general issue i hope you can fix it or just add option to turn offthe qvbr quality

02:31:03.053: amftest: AMF runtime version    : 1.4.24 build 0 raw 0
02:31:03.053: amftest: AMF compiletime version: 1.4.24 build 0 raw 0
02:31:03.058: amftest: SetProperty Usage 0
02:31:03.058: amftest: SetProperty Profile 100
02:31:03.058: amftest: SetProperty ProfileLevel 42
02:31:03.058: amftest: SetProperty LowLatencyInternal false
02:31:03.058: amftest: SetProperty RateControlMethod 0
02:31:03.059: amftest: SetProperty TargetBitrate 10000000
02:31:03.059: amftest: SetProperty PeakBitrate 30000000
02:31:03.059: amftest: SetProperty RateControlSkipFrameEnable false
02:31:03.059: amftest: SetProperty MinQP 18
02:31:03.059: amftest: SetProperty MaxQP 46
02:31:03.059: amftest: SetProperty QPI 26
02:31:03.059: amftest: SetProperty QPP 26
02:31:03.059: amftest: SetProperty QPB 26
02:31:03.059: amftest: SetProperty QvbrQualityLevel 51
02:31:03.069: amftest: Error: Plugin::Plugin: SetProperty QvbrQualityLevel 51
02:31:03.069: Stream output type 'rtmp_output' failed to start!

**Comment by bisher13** [comment]
obs:27.4.2
driver:22.3.2
GPU:RX580
amf ver:0.2

**Comment by Jocker73** [comment]
RX470 here, i get the same error

**Comment by Foxie117** [comment]
yup same

**Comment by e00E** [comment]
Could you try with the 0.2.1 release? You should still get the error message in the log about QvbrQualityLevel but the plugin should continue to work.

**Comment by bisher13** [comment]
21:43:12.501: Settings changed (outputs)
21:43:12.501: ------------------------------------------------
21:43:13.506: amftest: AMF runtime version    : 1.4.25 build 0 raw 0
21:43:13.506: amftest: AMF compiletime version: 1.4.24 build 0 raw 0
21:43:13.512: amftest: SetProperty OK Usage 0
21:43:13.512: amftest: SetProperty OK Profile 100
21:43:13.512: amftest: SetProperty OK ProfileLevel 42
21:43:13.512: amftest: SetProperty OK LowLatencyInternal false
21:43:13.512: amftest: SetProperty OK RateControlMethod 2
21:43:13.512: amftest: SetProperty OK TargetBitrate 10000000
21:43:13.512: amftest: SetProperty OK PeakBitrate 30000000
21:43:13.512: amftest: SetProperty OK RateControlSkipFrameEnable false
21:43:13.512: amftest: SetProperty OK MinQP 18
21:43:13.512: amftest: SetProperty OK MaxQP 46
21:43:13.512: amftest: SetProperty OK QPI 26
21:43:13.512: amftest: SetProperty OK QPP 26
21:43:13.512: amftest: SetProperty OK QPB 26
21:43:13.512: amftest: SetProperty ERR QvbrQualityLevel 23
21:43:13.512: amftest: SetProperty OK VBVBufferSize 20000000
21:43:13.512: amftest: SetProperty OK InitialVBVBufferFullness 64
21:43:13.512: amftest: SetProperty OK EnforceHRD true
21:43:13.512: amftest: SetProperty OK RateControlPreanalysisEnable true
21:43:13.512: amftest: SetProperty OK EnableVBAQ true
21:43:13.512: amftest: SetProperty OK FillerDataEnable true
21:43:13.512: amftest: SetProperty OK MaxNumRefFrames 16
21:43:13.513: amftest: SetProperty OK HeaderInsertionSpacing 0
21:43:13.513: amftest: SetProperty OK IDRPeriod 30
21:43:13.513: amftest: SetProperty OK SlicesPerFrame 1
21:43:13.513: amftest: SetProperty OK DeBlockingFilter true
21:43:13.513: amftest: SetProperty OK CABACEnable 1
21:43:13.513: amftest: SetProperty OK ScanType 0
21:43:13.513: amftest: SetProperty OK QualityPreset 0
21:43:13.513: amftest: SetProperty OK HalfPixel true
21:43:13.513: amftest: SetProperty OK QuarterPixel false
21:43:13.513: amftest: SetProperty ERR ColorBitDepth 16
21:43:13.513: amftest: SetProperty OK FrameRate (60000 / 1001)
21:43:13.513: amftest: SetProperty OK FullRangeColor false
21:43:13.513: amftest: SetProperty OK InColorProfile 1
21:43:13.513: amftest: SetProperty OK InColorTransferChar 1
21:43:13.513: amftest: SetProperty OK InColorPrimaries 0
21:43:13.513: amftest: SetProperty OK OutColorProfile 1
21:43:13.513: amftest: SetProperty OK OutColorTransferChar 1
21:43:13.513: amftest: SetProperty OK OutColorPrimaries 0
21:43:13.536: ---------------------------------
21:43:13.536: [FFmpeg aac encoder: 'Track1'] bitrate: 160, channels: 2, channel_layout: 3
21:43:13.536: 
21:43:13.544: ==== Recording Start ===============================================
21:43:13.544: [ffmpeg muxer: 'adv_file_output'] Writing file 'C:/Users/vfxno/Videos/2022-06-02_21-43-13.mkv'...
21:43:18.910: [ffmpeg muxer: 'adv_file_output'] Output of file 'C:/Users/vfxno/Videos/2022-06-02_21-43-13.mkv' stopped
21:43:18.910: Output 'adv_file_output': stopping
21:43:18.910: Output 'adv_file_output': Total frames output: 314
21:43:18.910: Output 'adv_file_output': Total drawn frames: 322
21:43:18.910: ==== Recording Stop ================================================

**Comment by bisher13** [comment]
right now the issue solved but idk if all the options working well as we want thx btw 😁

**Comment by bisher13** [comment]
if you see the log the qvbr written as error (amftest: SetProperty ERR QvbrQualityLevel 23)
