### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by geeshta** [e00E/obs-amf#29]
Hi,
can you add Linux support for the plugin? I tried building it form source but it curretly has windows exclusive dependencies like windows.h

**Comment by RAMChYLD** [comment]
> I'm not sure how much Linux support AMF has. I would like it to work on Linux but I don't know if that is possible.

Linux support is possible, but there is one major requirement, that the user must be running the amdgpu-pro drivers. This means sacrificing performance for quality as the amdgpu-pro drivers are tuned towards content creation, people have reported worse gaming frame rates under amdgpu-pro than under the open source amdgpu drivers.
