### ISSUE TITLE
When will the plugins work? on rx500 series video cards?

### ISSUE THREAD

**Issue by m9TM** [e00E/obs-amf#30]
Hello , when will the plugins work? on rx500 series video cards?

**Comment by bisher13** [comment]
actually that plug-in is dead since the maintainer left so don except smth special we just 1 chance that ffmpeg devs upgrade their library to 1.4.42 it gonna be more usable and working without issues 😁👌

**Comment by bisher13** [comment]
see this url i submitted request for amf devs they said the  upgrade gonna be soon as they said you csn react there so they can know how much people are interessted ❤️
https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/313

**Comment by e00E** [comment]
Try with the 0.2.1 release and post logs in a new issue please.
