### ISSUE TITLE
Missing/unlabeled quality adjustment slider for H264 QVBR quality 

### ISSUE THREAD

**Issue by cs9kc** [e00E/obs-amf#6]
Hello!  When using the "AMF AVC GPU" encoder, with "Quality Variable Bit Rate" selected as the rate control method, as mentioned on the top of [page 14 of the AMF_Video_Encode_API document](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/master/amf/doc/AMF_Video_Encode_API.pdf).

Does an existing slider change the value that QVBR looks at, or is QVBR expecting a discrete (from the others) value to be input?  Thanks for looking in to it!

Also also thank you for your work on this add-on, and for your Issues posts over on the AMF Github.  I look forward to the addition of Auto-LTR mode for H264 in AMF version 1.4.23 to your add-on, as it supposedly increases H264 encoder quality quite noticeably.  Thanks again!

**Comment by e00E** [comment]
QVBR was added with the newest version of AMF from ~2 weeks ago for which the plugin hasn't been updated.

**Comment by cs9kc** [comment]
Ah, okay, thank you!  I look forward to the next update!
