### ISSUE TITLE
obs 27.1.3 - amd driver - 2020-21.10.2 - RX 570 ( polaris ) not work

### ISSUE THREAD

**Issue by 52rpms** [e00E/obs-amf#7]
![amf](https://user-images.githubusercontent.com/96354105/146654482-1ba8443a-e085-45f7-af7e-465d308a250a.jpg)

**when i press record i get**
![amf1](https://user-images.githubusercontent.com/96354105/146654485-8a6f8492-4b02-4623-b94b-bf0f5d2290df.jpg)

my current obs log file

https://cutt.ly/8Y49r6b

**Comment by Jocker73** [comment]
I get the same error, i think it might not be compatible with polaris n older gens.

**Comment by 52rpms** [comment]
I do not think so , amd drivers are still on the 400/500 series.

**Comment by Unkorneglosk** [comment]
same with my RX 580

**Comment by bagusnl** [comment]
Same here on Vega 3 iGPU (R3-3200U//Picasso) with Adrenaline 22.1.1
